const anchor = (line: number) => `data-wf-src="playground/page.tsx:${line}:1" data-wf-section="sample-${line}"`;
const card = (title: string, text: string, line: number) => `<article ${anchor(line)} style="border:1px solid #d4d4d4;padding:32px;background:white"><h3 style="font-size:24px;margin:0 0 16px">${title}</h3><p style="font-size:18px;line-height:1.8;margin:0">${text}</p></article>`;

export const webpage = `<main ${anchor(1)} style="display:grid;grid-template-columns:minmax(0,1fr) 420px;width:100%;font-family:system-ui,sans-serif;color:#242424;background:white">
<div style="min-width:0">
<header ${anchor(2)} style="padding:32px 64px;border-bottom:1px solid #ddd;display:flex;justify-content:space-between;align-items:center"><strong style="font-size:28px">まちの学び舎</strong><nav style="font-size:18px">私たちについて　　講座一覧　　アクセス　　お問い合わせ</nav></header>
<section ${anchor(3)} style="padding:64px;display:grid;grid-template-columns:1.15fr 1fr;gap:48px;align-items:center"><div style="height:400px;background:#ddd;display:grid;place-items:center;font-size:20px;color:#555">メインビジュアル</div><div><p style="font-size:18px">OPEN CAMPUS 2026</p><h1 ${anchor(5)} style="font-size:44px;line-height:1.5;margin:24px 0">新しい一歩を、<br>この街から。</h1><p ${anchor(6)} style="font-size:22px;line-height:1.8">日常の中で、好きなことを見つける。<br>はじめての方も気軽に参加できます。</p><a ${anchor(7)} href="#courses" style="display:inline-block;padding:20px 48px;background:#333;color:white;text-decoration:none;font-size:20px">講座を探す →</a></div></section>
<section ${anchor(8)} style="padding:32px 64px;background:#f3f3f3;display:grid;grid-template-columns:repeat(3,1fr);gap:24px">${card('体験してみる','まずは一日、学びの時間を。',9)}${card('教室へのアクセス','駅から歩いて5分。',10)}${card('よくあるご質問','はじめての方はこちら。',11)}</section>
<section ${anchor(12)} id="courses" style="padding:80px 64px"><p style="font-size:18px;text-align:center">COURSES</p><h2 ${anchor(13)} style="font-size:36px;text-align:center;margin:24px 0 48px">あなたに合う学びを探す</h2><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:24px">${card('暮らしとデザイン','毎日を少し豊かにする、ものづくりの基本を学びます。',14)}${card('ことばと表現','ことばを通して、伝える楽しさを見つけます。',15)}${card('からだと健康','自分のペースで、心地よく体を動かしましょう。',16)}</div></section>
<section ${anchor(17)} style="padding:64px;background:#f6f6f6"><h2 style="font-size:32px;margin:0 0 32px">お知らせ</h2><p ${anchor(18)} style="padding:24px 0;border-bottom:1px solid #ccc;font-size:20px">2026.09.01　秋の体験講座の申し込みを開始しました</p><p ${anchor(19)} style="padding:24px 0;border-bottom:1px solid #ccc;font-size:20px">2026.08.20　新しい教室がオープンしました</p></section>
<footer ${anchor(20)} style="padding:64px;font-size:18px;border-top:1px solid #ddd">まちの学び舎　　お問い合わせ　　アクセス</footer>
</div>
<aside ${anchor(30)} style="padding:32px;background:#f5f5f5;border-left:1px solid #ddd;display:flex;flex-direction:column;gap:24px"><p style="margin:0;font-size:18px;line-height:1.8;color:#a42323">構成の確認用資料です。<br>色・写真はデザイン時に決定します。</p>${card('このページの役割','講座の魅力を伝え、体験の申し込みにつなげます。内容と順番をご確認ください。',31)}${card('最初に伝えること','写真と言葉で教室の雰囲気を伝えます。メインの導線は「講座を探す」です。',32)}${card('3つのご案内','よく使う入口を先にまとめます。気になる点は要素を選んでコメントしてください。',33)}${card('講座の見つけ方','講座の分類と説明文は打合せ後に調整します。',34)}</aside>
</main>`;

export const slides = [
`<div data-gg-src="slide:1" style="width:1920px;height:1080px;background:#f4f1ea;font-family:system-ui,sans-serif;color:#263c34;position:relative;overflow:hidden"><p data-gg-src="slide:1:eyebrow" style="position:absolute;left:120px;top:104px;font-size:24px;letter-spacing:4px">PROJECT PROPOSAL / 2026</p><h1 data-gg-src="slide:1:title" style="position:absolute;left:120px;top:280px;font-size:80px;line-height:1.5;margin:0">伝わる体験を、<br>いっしょにつくる。</h1><p data-gg-src="slide:1:body" style="position:absolute;left:128px;top:632px;font-size:30px;line-height:1.8">ウェブサイト リニューアルのご提案<br>2026年9月</p><div data-gg-src="slide:1:shape" style="position:absolute;left:1180px;top:200px;width:580px;height:640px;background:#d4dfd2;border-radius:280px 280px 16px 16px"></div><p style="position:absolute;left:128px;bottom:64px;font-size:22px">GROWGROUP　 /　PLAYGROUND</p></div>`,
`<div data-gg-src="slide:2" style="width:1920px;height:1080px;background:white;font-family:system-ui,sans-serif;color:#263c34;position:relative"><p style="position:absolute;left:120px;top:88px;font-size:24px">01 / APPROACH</p><h1 data-gg-src="slide:2:title" style="position:absolute;left:120px;top:180px;font-size:64px">迷わず、次の一歩へ。</h1><div style="position:absolute;left:120px;top:440px;width:1680px;display:grid;grid-template-columns:repeat(3,1fr);gap:40px">${card('理解する','誰に、何を伝えるか。使う人の視点から目的を整理します。',51)}${card('つくる','構成・言葉・デザインを一つの体験として組み立てます。',52)}${card('確かめる','実際に触れて、学んだことを次の改善へつなげます。',53)}</div></div>`,
];
